# Generated by Django 6.0.5 on 2026-06-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("question", models.CharField(max_length=220)),
                ("answer", models.TextField()),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HeroBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("eyebrow", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="hero/")),
                (
                    "primary_label",
                    models.CharField(default="Explore Properties", max_length=50),
                ),
                (
                    "primary_url",
                    models.CharField(default="/properties/", max_length=200),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("location", models.CharField(max_length=180)),
                ("summary", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("cover_image", models.ImageField(upload_to="projects/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                        ],
                        default="ongoing",
                        max_length=20,
                    ),
                ),
                (
                    "starting_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("map_url", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=300)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional Font Awesome class",
                        max_length=80,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="Siya Real Build", max_length=120),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Property that builds your future.", max_length=180
                    ),
                ),
                (
                    "about_title",
                    models.CharField(
                        default="Local expertise. Transparent property decisions.",
                        max_length=180,
                    ),
                ),
                (
                    "about_text",
                    models.TextField(
                        default="We help buyers, investors and businesses find the right real-estate opportunity."
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="site/")),
                ("favicon", models.ImageField(blank=True, upload_to="site/")),
                ("phone", models.CharField(default="+91 99999 99999", max_length=30)),
                (
                    "whatsapp_number",
                    models.CharField(default="919999999999", max_length=30),
                ),
                (
                    "email",
                    models.EmailField(default="info@siyarealbuild.com", max_length=254),
                ),
                ("address", models.TextField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                (
                    "seo_title",
                    models.CharField(
                        default="Siya Real Build | Property That Builds Your Future",
                        max_length=180,
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        default="Trusted plots, homes and commercial property opportunities.",
                        max_length=300,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("client_name", models.CharField(max_length=120)),
                ("client_role", models.CharField(blank=True, max_length=120)),
                ("quote", models.TextField()),
                ("photo", models.ImageField(blank=True, upload_to="testimonials/")),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("caption", models.CharField(blank=True, max_length=180)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="website.project",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertyListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("plot", "Residential Plot"),
                            ("house", "House / Villa"),
                            ("flat", "Flat / Apartment"),
                            ("commercial", "Commercial"),
                            ("land", "Land"),
                        ],
                        max_length=30,
                    ),
                ),
                ("location", models.CharField(max_length=180)),
                ("summary", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("cover_image", models.ImageField(upload_to="properties/")),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("area_sqft", models.PositiveIntegerField(blank=True, null=True)),
                ("bedrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bathrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="properties",
                        to="website.project",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.ImageField(upload_to="properties/gallery/")),
                ("caption", models.CharField(blank=True, max_length=180)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="website.propertylisting",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("interest", models.CharField(blank=True, max_length=120)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.propertylisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteVisitRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("preferred_date", models.DateField()),
                ("message", models.TextField(blank=True)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.propertylisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
