# Generated by Django 6.0.5 on 2026-06-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AchievementCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("value", models.PositiveIntegerField()),
                (
                    "suffix",
                    models.CharField(
                        blank=True, help_text="Examples: +, %, K+", max_length=12
                    ),
                ),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_image",
            field=models.ImageField(blank=True, upload_to="site/about/"),
        ),
    ]
