# Generated by Django 6.0.5 on 2026-06-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_achievementcounter_sitesettings_about_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="cta_label",
            field=models.CharField(default="Learn More", max_length=50),
        ),
        migrations.AddField(
            model_name="service",
            name="cta_url",
            field=models.CharField(default="/contact/", max_length=200),
        ),
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, upload_to="services/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_button_label",
            field=models.CharField(default="Know More About Us", max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_eyebrow",
            field=models.CharField(default="About Siya Real Build", max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_eyebrow",
            field=models.CharField(default="Start a Conversation", max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_text",
            field=models.CharField(
                default="Share your requirement and our property team will contact you.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_title",
            field=models.CharField(
                default="Tell us what you are looking for.", max_length=180
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="properties_eyebrow",
            field=models.CharField(default="Featured Opportunities", max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="properties_title",
            field=models.CharField(default="Find your next property", max_length=180),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="services_eyebrow",
            field=models.CharField(default="How We Help", max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="services_title",
            field=models.CharField(
                default="A simpler property journey", max_length=180
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Short icon character or emoji, for example: 🏠",
                max_length=80,
            ),
        ),
    ]
