# Generated by Django 6.0.5 on 2026-06-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_service_cta_label_service_cta_url_service_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="portal_login_label",
            field=models.CharField(default="Portal Login", max_length=60),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="portal_login_url",
            field=models.CharField(
                default="#",
                help_text="Add the CRM/portal login URL here.",
                max_length=300,
            ),
        ),
    ]
