# Generated by Django 6.0.5 on 2026-06-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_sitesettings_portal_login_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.CharField(
                choices=[
                    ("home", "Property / Home"),
                    ("verified", "Verified Selection"),
                    ("visit", "Site Visit"),
                    ("document", "Documentation"),
                    ("investment", "Investment"),
                    ("support", "Support"),
                ],
                default="home",
                max_length=30,
            ),
        ),
    ]
