# Generated by Django 6.0.5 on 2026-06-14 13:03

import django.db.models.deletion
from django.db import migrations, models


def migrate_categories(apps, schema_editor):
    PropertyCategory = apps.get_model("website", "PropertyCategory")
    PropertyListing = apps.get_model("website", "PropertyListing")
    definitions = [
        ("plot", "Residential Plot", "plot"),
        ("house", "House / Villa", "home"),
        ("flat", "Flat / Apartment", "building"),
        ("commercial", "Commercial Property", "commercial"),
        ("land", "Land", "land"),
    ]
    categories = {}
    for order, (slug, name, icon) in enumerate(definitions, 1):
        categories[slug], _ = PropertyCategory.objects.get_or_create(
            slug=slug,
            defaults={"name": name, "icon": icon, "sort_order": order},
        )
    for listing in PropertyListing.objects.all():
        listing.category_new = categories.get(listing.category, categories["plot"])
        listing.save(update_fields=["category_new"])


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_galleryitem_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.CharField(blank=True, max_length=240)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("plot", "Plot"),
                            ("home", "Home"),
                            ("building", "Building"),
                            ("commercial", "Commercial"),
                            ("land", "Land"),
                        ],
                        default="home",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="propertylisting",
            name="category_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="website.propertycategory",
            ),
        ),
        migrations.RunPython(migrate_categories, migrations.RunPython.noop),
        migrations.RemoveField(model_name="propertylisting", name="category"),
        migrations.RenameField(
            model_name="propertylisting", old_name="category_new", new_name="category"
        ),
    ]
