# Generated by Django 6.0.5 on 2026-06-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_propertycategory_alter_propertylisting_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertylisting",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="website.propertycategory",
            ),
        ),
    ]
