# Generated by Django 6.0.5 on 2026-06-15 03:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_alter_propertylisting_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="icon",
        ),
    ]
