# Generated by Django 6.0.5 on 2026-06-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_remove_service_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhyChooseUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=300)),
                ("image", models.ImageField(blank=True, upload_to="why-choose/")),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="why_choose_eyebrow",
            field=models.CharField(default="Why Choose Siya", max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="why_choose_text",
            field=models.CharField(
                default="Clear advice, verified opportunities and dependable support at every step.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="why_choose_title",
            field=models.CharField(
                default="Property guidance you can trust", max_length=180
            ),
        ),
    ]
