# Generated by Django 6.0.5 on 2026-06-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_whychooseus_sitesettings_why_choose_eyebrow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_banner_image",
            field=models.ImageField(blank=True, upload_to="site/about/banner/"),
        ),
    ]
