# Generated by Django 6.0.5 on 2026-06-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_sitesettings_about_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_story_image",
            field=models.ImageField(blank=True, upload_to="site/about/story/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_story_text",
            field=models.TextField(
                default="Siya Real Build helps buyers and investors discover suitable properties with transparent guidance, local expertise and dependable support."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_story_title",
            field=models.CharField(
                default="Building trust through better property decisions",
                max_length=220,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission_image",
            field=models.ImageField(blank=True, upload_to="site/about/mission/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission_text",
            field=models.TextField(
                default="To make every property journey clear, reliable and confidently informed."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission_title",
            field=models.CharField(default="Our Mission", max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="values_image",
            field=models.ImageField(blank=True, upload_to="site/about/values/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="values_text",
            field=models.TextField(
                default="Integrity, client-first guidance, local expertise, clear communication and dependable support."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="values_title",
            field=models.CharField(default="Our Values", max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_image",
            field=models.ImageField(blank=True, upload_to="site/about/vision/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_text",
            field=models.TextField(
                default="To become a trusted real-estate partner known for transparency, quality opportunities and lasting client relationships."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_title",
            field=models.CharField(default="Our Vision", max_length=120),
        ),
    ]
