# Generated by Django 6.0.5 on 2026-06-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_sitesettings_about_story_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="founder_designation",
            field=models.CharField(
                default="Founder & Managing Director", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="founder_image",
            field=models.ImageField(blank=True, upload_to="site/about/founder/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="founder_message",
            field=models.TextField(
                default="Our purpose is to help every client make a confident property decision through honest guidance, clear information and dependable support."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="founder_name",
            field=models.CharField(default="Founder, Siya Real Build", max_length=120),
        ),
    ]
