# Generated by Django 6.0.5 on 2026-06-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_sitesettings_founder_designation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="second_founder_designation",
            field=models.CharField(default="Co-Founder & Director", max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="second_founder_image",
            field=models.ImageField(blank=True, upload_to="site/about/founder/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="second_founder_message",
            field=models.TextField(
                default="We are committed to building lasting client relationships through transparent service, quality opportunities and responsive support."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="second_founder_name",
            field=models.CharField(
                default="Co-Founder, Siya Real Build", max_length=120
            ),
        ),
    ]
