# Generated by Django 6.0.5 on 2026-06-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_sitesettings_second_founder_designation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="properties_banner_image",
            field=models.ImageField(blank=True, upload_to="site/properties/banner/"),
        ),
    ]
