# Generated by Django 6.0.5 on 2026-06-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_sitesettings_properties_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertylisting",
            name="amenities",
            field=models.TextField(blank=True, help_text="Enter one amenity per line."),
        ),
        migrations.AddField(
            model_name="propertylisting",
            name="layout_image",
            field=models.ImageField(blank=True, upload_to="properties/layouts/"),
        ),
        migrations.AddField(
            model_name="propertylisting",
            name="map_url",
            field=models.URLField(blank=True),
        ),
    ]
