# Generated by Django 6.0.5 on 2026-06-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0016_propertylisting_amenities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="services_banner_image",
            field=models.ImageField(blank=True, upload_to="site/services/banner/"),
        ),
    ]
