# Generated by Django 6.0.5 on 2026-06-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_sitesettings_services_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="team_banner_image",
            field=models.ImageField(blank=True, upload_to="site/team/banner/"),
        ),
    ]
