# Generated by Django 6.0.5 on 2026-06-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0018_sitesettings_team_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="gallery_banner_image",
            field=models.ImageField(blank=True, upload_to="site/gallery/banner/"),
        ),
    ]
