# Generated by Django 6.0.5 on 2026-06-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0019_sitesettings_gallery_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="business_hours",
            field=models.CharField(
                default="Monday - Saturday, 10:00 AM - 7:00 PM", max_length=180
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_banner_image",
            field=models.ImageField(blank=True, upload_to="site/contact/banner/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="office_map_url",
            field=models.URLField(blank=True),
        ),
    ]
