# Generated by Django 6.0.5 on 2026-06-15 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0020_sitesettings_business_hours_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("property_title", models.CharField(max_length=180)),
                ("location", models.CharField(max_length=180)),
                (
                    "expected_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("area_sqft", models.PositiveIntegerField(blank=True, null=True)),
                ("bedrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bathrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="property-submissions/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="website.propertycategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
