# Generated by Django 6.0.5 on 2026-06-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0021_propertysubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="footer_contact_title",
            field=models.CharField(default="Contact", max_length=80),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_credit_name",
            field=models.CharField(default="The Webfix", max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_credit_text",
            field=models.CharField(default="Design and developed by", max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_credit_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_explore_title",
            field=models.CharField(default="Explore", max_length=80),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_property_types_title",
            field=models.CharField(default="Property Types", max_length=80),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_whatsapp_button",
            field=models.CharField(default="Start Conversation", max_length=80),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_whatsapp_eyebrow",
            field=models.CharField(default="Scan & Chat", max_length=80),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_whatsapp_text",
            field=models.CharField(
                default="Get property details and schedule a site visit.",
                max_length=220,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_whatsapp_title",
            field=models.CharField(default="Connect on WhatsApp", max_length=120),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="post_property_label",
            field=models.CharField(default="Post Property", max_length=60),
        ),
    ]
