# Generated by Django 6.0.5 on 2026-06-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0022_sitesettings_footer_contact_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="post_property_banner_image",
            field=models.ImageField(blank=True, upload_to="site/post-property/banner/"),
        ),
    ]
