from django.urls import path

from accounts.view_modules import events_meetings, owner_configuration, owner_email_changes, owner_operations, owner_reviews


urlpatterns = [
    path("owner/operations/", owner_operations.owner_operations_dashboard, name="owner_operations_dashboard"),
    path("owner/codes/", owner_reviews.owner_codes, name="owner_codes"),
    path("owner/codes/assigned/", owner_reviews.owner_assigned_codes, name="owner_assigned_codes"),
    path("owner/codes/rules/", owner_reviews.owner_serial_rules, name="owner_serial_rules"),
    path("owner/requests/", owner_reviews.owner_requests, name="owner_requests"),
    path("owner/requests/signups/", owner_reviews.owner_signup_request_list, name="owner_signup_request_list"),
    path("owner/requests/signups/bulk-delete/", owner_reviews.owner_signup_request_bulk_delete, name="owner_signup_request_bulk_delete"),
    path("owner/requests/signup/<int:request_id>/", owner_reviews.owner_signup_request_detail, name="owner_signup_request_detail"),
    path("owner/meetings/", events_meetings.owner_meetings, name="owner_meetings"),
    path("owner/meetings/new/", events_meetings.owner_meeting_create, name="owner_meeting_create"),
    path("owner/meetings/<int:meeting_id>/", events_meetings.owner_meeting_detail, name="owner_meeting_detail"),
    path("owner/meetings/<int:meeting_id>/edit/", events_meetings.owner_meeting_edit, name="owner_meeting_edit"),
    path("owner/events/", events_meetings.owner_events, name="owner_events"),
    path("owner/events/new/", events_meetings.owner_event_create, name="owner_event_create"),
    path("owner/events/<int:event_id>/edit/", events_meetings.owner_event_edit, name="owner_event_edit"),
    path("owner/events/<int:event_id>/", events_meetings.owner_event_detail, name="owner_event_detail"),
    path("owner/marketing/", owner_configuration.owner_marketing_dashboard, name="owner_marketing_dashboard"),
    path("owner/referrals/", owner_configuration.owner_referrals, name="owner_referrals"),
    path("owner/targets/", owner_configuration.owner_targets, name="owner_targets"),
    path("owner/targets/<int:target_id>/", owner_configuration.owner_target_detail, name="owner_target_detail"),
    path("owner/targets/<int:target_id>/edit/", owner_configuration.owner_target_edit, name="owner_target_edit"),
    path("owner/targets/<int:target_id>/delete/", owner_configuration.owner_target_delete, name="owner_target_delete"),
    path("owner/popups/", owner_configuration.owner_popups, name="owner_popups"),
    path("owner/popups/new/", owner_configuration.owner_popup_create, name="owner_popup_create"),
    path("owner/popups/<int:popup_id>/edit/", owner_configuration.owner_popup_edit, name="owner_popup_edit"),
    path("owner/popups/<int:popup_id>/", owner_configuration.owner_popup_detail, name="owner_popup_detail"),
    path("owner/popups/<int:popup_id>/track/<str:action>/", owner_configuration.popup_track, name="popup_track"),
    path("owner/role-matrix/", owner_operations.owner_role_matrix, name="owner_role_matrix"),
    path("owner/email-changes/", owner_email_changes.owner_email_changes, name="owner_email_changes"),
    path("owner/email-changes/new/", owner_email_changes.owner_email_change_create, name="owner_email_change_create"),
    path("owner/support/", owner_operations.owner_support, name="owner_support"),
    path("owner/office-locations/", owner_operations.owner_office_locations, name="owner_office_locations"),
    path("owner/audit-logs/", owner_operations.owner_audit_logs, name="owner_audit_logs"),
    path("owner/notifications/", owner_operations.owner_notification_deliveries, name="owner_notification_deliveries"),
]
