# Generated by Django 6.0.5 on 2026-06-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_emailotp_id_alter_signuprequest_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticationSupportRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("contact", models.CharField(blank=True, max_length=160)),
                ("issue", models.TextField()),
                ("page_url", models.CharField(blank=True, max_length=300)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
