# Generated by Django 6.0.5 on 2026-06-03 04:27

from django.db import migrations, models


def collapse_company_profiles(apps, schema_editor):
    CompanyProfile = apps.get_model("accounts", "CompanyProfile")
    UserProfile = apps.get_model("accounts", "UserProfile")
    EmployeeInvite = apps.get_model("accounts", "EmployeeInvite")

    companies = list(CompanyProfile.objects.order_by("id"))
    if not companies:
        return

    primary = companies[0]
    primary.singleton_key = True
    primary.save(update_fields=["singleton_key"])

    duplicate_ids = [company.id for company in companies[1:]]
    if duplicate_ids:
        UserProfile.objects.filter(company_id__in=duplicate_ids).update(company_id=primary.id)
        EmployeeInvite.objects.filter(company_id__in=duplicate_ids).update(company_id=primary.id)
        CompanyProfile.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_companyprofile_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="singleton_key",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.RunPython(collapse_company_profiles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="companyprofile",
            name="singleton_key",
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
    ]
