# Generated by Django 6.0.5 on 2026-06-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_companyprofile_singleton_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="owner",
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="cin_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="email_2",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="email_3",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="logo",
            field=models.ImageField(blank=True, upload_to="company/"),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="pan_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="phone_2",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="phone_3",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="pincode",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="tagline",
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
