# Generated by Django 6.0.5 on 2026-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_employeeinvite_is_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="bank_ifsc",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="upi_id",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
