# Generated by Django 6.0.5 on 2026-06-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_companyprofile_bank_account_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="holiday_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="weekly_off_days",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
