# Generated by Django 5.2.8 on 2026-06-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_companyprofile_closing_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="channel_partner_reference",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="government_id_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="government_id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aadhaar", "Aadhaar"),
                    ("voter_id", "Voter ID"),
                    ("passport", "Passport"),
                    ("driving_license", "Driving License"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pan_number",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pincode",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reporting_manager",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="territory",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="work_location",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
