# Generated by Django 5.2.8 on 2026-06-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_userprofile_channel_partner_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="aadhaar_document",
            field=models.FileField(blank=True, upload_to="profiles/documents/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="aadhaar_number",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bank_ifsc",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="blood_group",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("other", "Other"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pan_document",
            field=models.FileField(blank=True, upload_to="profiles/documents/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="personal_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
