# Generated by Django 5.2.8 on 2026-06-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_userprofile_aadhaar_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="aadhaar_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
