# Generated by Django 5.2.8 on 2026-06-04 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_signuprequestownermessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamEmailMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("company_owner", "Company Owner"),
                            ("manager", "Manager"),
                            ("tl", "TL"),
                            ("executive", "Executive"),
                            ("channel_partner", "Channel Partner"),
                        ],
                        max_length=32,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=80)),
                ("subject", models.CharField(max_length=180)),
                ("message", models.TextField()),
                ("recipients", models.JSONField(blank=True, default=list)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_emails",
                        to="accounts.companyprofile",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
