# Generated by Django 5.2.8 on 2026-06-04 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_employeerolechangerequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designationcoderule",
            name="padding",
        ),
        migrations.AddField(
            model_name="companyevent",
            name="caption",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="companyevent",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="events/covers/"),
        ),
        migrations.AddField(
            model_name="companyevent",
            name="roles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="companyevent",
            name="show_as_popup",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CompanyEventGalleryImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="events/gallery/")),
                ("caption", models.CharField(blank=True, max_length=180)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="accounts.companyevent",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
