# Generated by Django 5.2.8 on 2026-06-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_remove_designationcoderule_padding_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanyEventGalleryImage",
        ),
    ]
