# Generated by Django 5.2.8 on 2026-06-06 02:17

from django.db import migrations, models


def copy_existing_referral_values(apps, schema_editor):
    ReferralSetting = apps.get_model("accounts", "ReferralSetting")
    ReferralReward = apps.get_model("accounts", "ReferralReward")
    for setting in ReferralSetting.objects.all():
        setting.referrer_reward_amount = setting.bonus_amount
        setting.referred_reward_amount = setting.bonus_amount
        setting.referrer_coupon_code = setting.coupon_code
        setting.referred_coupon_code = setting.coupon_code
        setting.save(update_fields=[
            "referrer_reward_amount",
            "referred_reward_amount",
            "referrer_coupon_code",
            "referred_coupon_code",
        ])
    for reward in ReferralReward.objects.all():
        reward.referrer_coupon_code = reward.coupon_code
        reward.referred_coupon_code = reward.coupon_code
        reward.save(update_fields=["referrer_coupon_code", "referred_coupon_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_referralreward"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralreward",
            name="referred_coupon_code",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="referralreward",
            name="referrer_coupon_code",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="referralsetting",
            name="referred_coupon_code",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="referralsetting",
            name="referred_reward_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="referralsetting",
            name="referrer_coupon_code",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="referralsetting",
            name="referrer_reward_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(copy_existing_referral_values, migrations.RunPython.noop),
    ]
