# Generated by Django 5.2.8 on 2026-06-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_normalize_employee_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="authenticationsupportrequest",
            name="owner_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="authenticationsupportrequest",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roletarget",
            name="current_value",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roletarget",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="roletarget",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("paused", "Paused"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
