# Generated by Django 5.2.8 on 2026-06-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_authenticationsupportrequest_owner_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralreward",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="referralreward",
            name="payout_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="referralreward",
            name="payout_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                    ("hold", "On hold"),
                    ("cancelled", "Cancelled"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="referralreward",
            name="referred_coupon_redeemed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="referralreward",
            name="referrer_coupon_redeemed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="softwarepopup",
            name="clicks",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="softwarepopup",
            name="closes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="softwarepopup",
            name="cta_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="softwarepopup",
            name="cta_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="softwarepopup",
            name="impressions",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
