# Generated by Django 6.0.5 on 2026-06-01 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("villa", "Villa"),
                            ("plot", "Plot"),
                            ("commercial", "Commercial"),
                        ],
                        max_length=30,
                    ),
                ),
                ("city", models.CharField(max_length=80)),
                ("address", models.CharField(max_length=220)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("area_sqft", models.PositiveIntegerField()),
                ("bedrooms", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("negotiation", "Negotiation"),
                            ("sold", "Sold"),
                            ("rented", "Rented"),
                        ],
                        default="available",
                        max_length=30,
                    ),
                ),
                ("lead_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
