# Generated by Django 5.2.8 on 2026-06-06 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_property_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="amenities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="available_plots",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="balconies",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="bathrooms",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="builtup_area_sqft",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="carpet_area_sqft",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="category",
            field=models.CharField(
                choices=[
                    ("colony", "Colony"),
                    ("plot", "Plot"),
                    ("resale_plot", "Resale Plot"),
                    ("flat", "Flat"),
                    ("residential_house", "Residential House"),
                    ("commercial_shop", "Commercial Shop"),
                    ("row_house", "Row House"),
                    ("villa", "Villa"),
                    ("farm_house", "Farm House"),
                    ("office", "Office"),
                    ("warehouse", "Warehouse"),
                    ("agricultural_land", "Agricultural Land"),
                ],
                default="plot",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="colony_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="property",
            name="construction_status",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="property",
            name="contact_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="property",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="property",
            name="development_status",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="property",
            name="facing",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="property",
            name="floor_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="furnishing",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="property",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="khasra_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="property",
            name="landmark",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="property",
            name="legal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="legal_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("clear", "Clear"),
                    ("under_review", "Under Review"),
                    ("disputed", "Disputed"),
                    ("mortgaged", "Mortgaged"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="length_ft",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="listing_for",
            field=models.CharField(
                choices=[("sale", "Sale"), ("rent", "Rent"), ("lease", "Lease")],
                default="sale",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="locality",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="property",
            name="map_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="parking_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="possession_status",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="property",
            name="price_per_sqft",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="property",
            name="registry_status",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="property",
            name="rera_number",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="property",
            name="road_width_ft",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="tcp_approval_number",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="property",
            name="total_floors",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="total_plots",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="property",
            name="width_ft",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(max_length=260),
        ),
        migrations.AlterField(
            model_name="property",
            name="area_sqft",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("colony", "Colony"),
                    ("plot", "Plot"),
                    ("resale_plot", "Resale Plot"),
                    ("flat", "Flat"),
                    ("residential_house", "Residential House"),
                    ("commercial_shop", "Commercial Shop"),
                    ("row_house", "Row House"),
                    ("villa", "Villa"),
                    ("farm_house", "Farm House"),
                    ("office", "Office"),
                    ("warehouse", "Warehouse"),
                    ("agricultural_land", "Agricultural Land"),
                ],
                default="plot",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("hold", "Hold"),
                    ("negotiation", "Negotiation"),
                    ("sold", "Sold"),
                    ("rented", "Rented"),
                ],
                default="available",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="PropertyDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("rera", "RERA"),
                            ("tcp", "T&CP"),
                            ("registry", "Registry"),
                            ("map", "Map / Layout"),
                            ("legal", "Legal Document"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=160)),
                ("file", models.FileField(upload_to="properties/documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["document_type", "id"],
            },
        ),
        migrations.CreateModel(
            name="PropertyPhoto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="properties/photos/")),
                ("caption", models.CharField(blank=True, max_length=160)),
                ("is_primary", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "id"],
            },
        ),
        migrations.CreateModel(
            name="ColonyPlot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plot_number", models.CharField(max_length=40)),
                ("area_sqft", models.PositiveIntegerField(default=0)),
                (
                    "length_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "width_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("facing", models.CharField(blank=True, max_length=40)),
                (
                    "road_width_ft",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("hold", "Hold"),
                            ("sold", "Sold"),
                            ("reserved", "Reserved"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=220)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plots",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["plot_number"],
                "unique_together": {("property", "plot_number")},
            },
        ),
    ]
