# Generated by Django 5.2.8 on 2026-06-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_propertyvisit"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="amenity_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="corner_plot_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="garden_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="garden_facing_plot_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="property",
            name="nearby_commercial",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="nearby_connectivity",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="nearby_education",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="nearby_healthcare",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="nearby_landmarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="nearby_residential",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="plc_rules",
            field=models.TextField(blank=True),
        ),
    ]
