# Generated by Django 5.2.8 on 2026-06-11 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_referralreward_paid_at_referralreward_payout_note_and_more"),
        (
            "properties",
            "0006_property_assigned_to_propertyvisit_conversion_note_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="colonyplot",
            name="base_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="colonyplot",
            name="block",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="colonyplot",
            name="custom_category",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="colonyplot",
            name="extra_charges",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="colonyplot",
            name="is_corner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="colonyplot",
            name="is_garden_facing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="colonyplot",
            name="is_main_road",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="colonyplot",
            name="plc_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="colonyplot",
            name="plot_category",
            field=models.CharField(
                choices=[
                    ("residential", "Residential"),
                    ("commercial", "Commercial"),
                    ("lig", "LIG"),
                    ("mig", "MIG"),
                    ("hig", "HIG"),
                    ("ews", "EWS"),
                    ("premium", "Premium"),
                    ("custom", "Custom"),
                ],
                default="residential",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="base_rate_per_sqft",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="property",
            name="commercial_rate_per_sqft",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="property",
            name="corner_plc_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="property",
            name="custom_amenities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="property",
            name="development_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="property",
            name="electricity_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="property",
            name="ews_rate_per_sqft",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="property",
            name="garden_facing_plc_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="property",
            name="hig_rate_per_sqft",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="property",
            name="lig_rate_per_sqft",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="property",
            name="main_road_plc_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="property",
            name="maintenance_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="property",
            name="mig_rate_per_sqft",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="property",
            name="other_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="property",
            name="registry_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="property",
            name="residential_rate_per_sqft",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="property",
            name="selected_amenities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="property",
            name="wide_road_plc_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="colonyplot",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("hold", "Hold"),
                    ("sold", "Sold"),
                    ("reserved", "Reserved"),
                    ("booked", "Booked"),
                    ("cancelled", "Cancelled"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS "properties_plotstatushistory" (
                        "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                        "from_status" varchar(20) NOT NULL,
                        "to_status" varchar(20) NOT NULL,
                        "note" text NOT NULL,
                        "created_at" datetime NOT NULL,
                        "changed_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED,
                        "plot_id" integer NOT NULL REFERENCES "properties_colonyplot" ("id") DEFERRABLE INITIALLY DEFERRED
                    )
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="PlotStatusHistory",
                    fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("hold", "Hold"),
                            ("sold", "Sold"),
                            ("reserved", "Reserved"),
                            ("booked", "Booked"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("hold", "Hold"),
                            ("sold", "Sold"),
                            ("reserved", "Reserved"),
                            ("booked", "Booked"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="properties.colonyplot",
                    ),
                ),
                    ],
                    options={
                        "ordering": ["-created_at"],
                    },
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyDeveloper",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("company_name", models.CharField(blank=True, max_length=180)),
                ("contact_person", models.CharField(blank=True, max_length=140)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("office_address", models.CharField(blank=True, max_length=260)),
                ("rera_number", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_developers",
                        to="accounts.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.AddField(
            model_name="property",
            name="developer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties",
                to="properties.propertydeveloper",
            ),
        ),
    ]
