# Generated by Django 5.2.8 on 2026-06-12 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_repair_plotstatushistory_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="development_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="property",
            name="video_link",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="PropertyCommissionRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("company_owner", "Company Owner"),
                            ("manager", "Manager"),
                            ("tl", "TL"),
                            ("executive", "Executive"),
                            ("channel_partner", "Channel Partner"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("per_sqft", "Per sqft"),
                            ("fixed_amount", "Fixed amount"),
                        ],
                        default="percentage",
                        max_length=30,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("note", models.CharField(blank=True, max_length=220)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_rules",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["role"],
                "unique_together": {("property", "role")},
            },
        ),
    ]
