# Generated by Django 5.2.8 on 2026-06-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_property_development_name_property_video_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="video_links",
            field=models.TextField(blank=True),
        ),
    ]
