# Generated by Django 5.2.8 on 2026-06-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_property_video_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="colonyplot",
            name="is_wide_road",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="commission_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="commission_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="colonyplot",
            name="facing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("east", "East"),
                    ("west", "West"),
                    ("north", "North"),
                    ("south", "South"),
                    ("north_east", "North East"),
                    ("north_west", "North West"),
                    ("south_east", "South East"),
                    ("south_west", "South West"),
                    ("park_facing", "Park Facing"),
                    ("garden_facing", "Garden Facing"),
                    ("main_road", "Main Road"),
                    ("corner", "Corner"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="development_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pre_launch", "Pre Launch"),
                    ("launched", "Launched"),
                    ("under_development", "Under Development"),
                    ("developed", "Developed"),
                    ("ready_possession", "Ready Possession"),
                ],
                max_length=120,
            ),
        ),
    ]
