# Generated by Django 5.2.8 on 2026-06-12 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0015_plotbooking_balance_amount_plotbooking_paid_amount_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertydocument",
            options={"ordering": ["document_type", "review_status", "id"]},
        ),
        migrations.AddField(
            model_name="propertydocument",
            name="document_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="propertydocument",
            name="expires_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="propertydocument",
            name="issued_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="propertydocument",
            name="review_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="propertydocument",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="propertydocument",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="propertydocument",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_property_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="BookingAgreement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agreement_type",
                    models.CharField(
                        choices=[
                            ("booking", "Booking Agreement"),
                            ("sale", "Sale Agreement"),
                            ("registry", "Registry Deed"),
                            ("possession", "Possession Letter"),
                            ("other", "Other"),
                        ],
                        default="booking",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent to Client"),
                            ("signed", "Signed"),
                            ("registered", "Registered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, upload_to="properties/agreements/"),
                ),
                ("agreement_number", models.CharField(blank=True, max_length=120)),
                ("stamp_number", models.CharField(blank=True, max_length=120)),
                ("prepared_on", models.DateField(blank=True, null=True)),
                ("signed_on", models.DateField(blank=True, null=True)),
                ("registered_on", models.DateField(blank=True, null=True)),
                ("registration_office", models.CharField(blank=True, max_length=160)),
                ("next_action_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="properties.plotbooking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_booking_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_booking_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-prepared_on", "-created_at"],
            },
        ),
    ]
