# Generated by Django 5.2.8 on 2026-06-12 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0017_misreportsnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyCommissionPayout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("company_owner", "Company Owner"),
                            ("manager", "Manager"),
                            ("tl", "TL"),
                            ("executive", "Executive"),
                            ("channel_partner", "Channel Partner"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("percentage", "Percentage"),
                            ("per_sqft", "Per sqft"),
                            ("fixed_amount", "Fixed amount"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "rule_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("payout_reference", models.CharField(blank=True, max_length=120)),
                ("note", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_payouts",
                        to="properties.plotbooking",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_property_commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_property_commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["booking_id", "role"],
                "unique_together": {("booking", "role")},
            },
        ),
    ]
