# Generated by Django 5.2.8 on 2026-06-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0018_propertycommissionpayout"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotbooking",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="coupon_discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
