# Generated by Django 5.2.8 on 2026-06-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0019_plotbooking_coupon_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyvisit",
            name="image",
            field=models.ImageField(blank=True, upload_to="properties/visits/"),
        ),
    ]
