# Generated by Django 5.2.8 on 2026-06-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0020_propertyvisit_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Booking Requested"),
                    ("draft", "Draft"),
                    ("booked", "Booked"),
                    ("cancelled", "Cancelled"),
                    ("converted", "Converted to Sale"),
                ],
                default="booked",
                max_length=20,
            ),
        ),
    ]
