# Generated by Django 5.2.8 on 2026-06-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0021_alter_plotbooking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotbooking",
            name="plot_area_sqft",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="plot_facing",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="plot_length_ft",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="plot_width_ft",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="plotquotation",
            name="plot_area_sqft",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plotquotation",
            name="plot_facing",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="plotquotation",
            name="plot_length_ft",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="plotquotation",
            name="plot_width_ft",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
