# Generated by Django 5.2.8 on 2026-06-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0022_plotbooking_plot_area_sqft_plotbooking_plot_facing_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="colonyplot",
            name="plc_rate",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="PLC (%)"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="corner_plc_rate",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Corner PLC (%)"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="garden_facing_plc_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Garden facing PLC (%)",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="main_road_plc_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Main road PLC (%)",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="wide_road_plc_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Wide road PLC (%)",
            ),
        ),
    ]
