# Generated by Django 5.2.8 on 2026-06-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0024_alter_colonyplot_plc_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotbooking",
            name="client_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="discount_reason",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="government_id_number",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="government_id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aadhaar", "Aadhaar Card"),
                    ("pan", "PAN Card"),
                    ("passport", "Passport"),
                    ("driving_license", "Driving License"),
                    ("voter_id", "Voter ID"),
                    ("other", "Other Government ID"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="payment_proof",
            field=models.ImageField(blank=True, upload_to="properties/booking-proofs/"),
        ),
        migrations.AddField(
            model_name="plotbooking",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
