# Generated by Django 5.2.8 on 2026-06-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0025_plotbooking_client_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotbooking",
            name="government_id_document",
            field=models.FileField(
                blank=True, upload_to="properties/booking-govt-ids/"
            ),
        ),
    ]
