from django.urls import path

from . import views

app_name = "properties"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("reports/owner-mis/", views.owner_mis_report, name="owner_mis_report"),
    path("properties/", views.property_list, name="list"),
    path("properties/export/", views.property_export, name="export"),
    path("properties/plot-finder/", views.plot_finder, name="plot_finder"),
    path("quotations/", views.quotation_list, name="quotation_list"),
    path("bookings/", views.booking_list, name="booking_list"),
    path("bookings/<int:booking_id>/", views.booking_detail, name="booking_detail"),
    path("properties/commission-rules/", views.commission_rules, name="commission_rules"),
    path("properties/bulk-action/", views.property_bulk_action, name="bulk_action"),
    path("properties/new/", views.property_create, name="create"),
    path("developers/new/", views.developer_create, name="developer_create"),
    path("properties/<int:property_id>/", views.property_detail, name="detail"),
    path("properties/<int:property_id>/pdf/", views.property_pdf, name="property_pdf"),
    path("properties/<int:property_id>/edit/", views.property_edit, name="edit"),
    path("properties/<int:property_id>/archive/", views.property_archive, name="archive"),
    path("properties/<int:property_id>/restore/", views.property_restore, name="restore"),
    path("properties/<int:property_id>/delete/", views.property_delete, name="delete"),
    path("properties/<int:property_id>/photos/cover/upload/", views.property_cover_photo_upload, name="cover_photo_upload"),
    path("properties/<int:property_id>/photos/<int:photo_id>/cover/", views.property_photo_primary, name="photo_primary"),
    path("properties/<int:property_id>/photos/<int:photo_id>/delete/", views.property_photo_delete, name="photo_delete"),
    path("properties/<int:property_id>/documents/<int:document_id>/delete/", views.property_document_delete, name="document_delete"),
    path("properties/<int:property_id>/documents/upload/", views.property_documents_upload, name="documents_upload"),
    path("properties/<int:property_id>/documents/<int:document_id>/review/", views.property_document_review, name="document_review"),
    path("properties/<int:property_id>/documents/<int:document_id>/download/", views.property_document_download, name="document_download"),
    path("properties/<int:property_id>/plots/new/", views.colony_plot_create, name="plot_create"),
    path("properties/<int:property_id>/plots/<int:plot_id>/edit/", views.colony_plot_edit, name="plot_edit"),
    path("properties/<int:property_id>/plots/<int:plot_id>/quotations/new/", views.plot_quotation_create, name="plot_quotation_create"),
    path("properties/<int:property_id>/plots/<int:plot_id>/quotations/<int:quotation_id>/pdf/", views.plot_quotation_pdf, name="plot_quotation_pdf"),
    path("properties/<int:property_id>/plots/<int:plot_id>/quotations/<int:quotation_id>/edit/", views.plot_quotation_edit, name="plot_quotation_edit"),
    path("properties/<int:property_id>/plots/<int:plot_id>/bookings/new/", views.plot_booking_create, name="plot_booking_create"),
    path("properties/<int:property_id>/plots/<int:plot_id>/bookings/<int:booking_id>/pdf/", views.plot_booking_pdf, name="plot_booking_pdf"),
    path("properties/<int:property_id>/plots/<int:plot_id>/bookings/<int:booking_id>/edit/", views.plot_booking_edit, name="plot_booking_edit"),
    path("properties/<int:property_id>/plots/<int:plot_id>/bookings/<int:booking_id>/approve/", views.booking_request_approve, name="booking_request_approve"),
    path("properties/<int:property_id>/plots/<int:plot_id>/bookings/<int:booking_id>/installments/new/", views.booking_installment_create, name="booking_installment_create"),
    path("properties/<int:property_id>/plots/<int:plot_id>/bookings/<int:booking_id>/payments/new/", views.booking_payment_create, name="booking_payment_create"),
    path("properties/<int:property_id>/plots/<int:plot_id>/bookings/<int:booking_id>/agreements/new/", views.booking_agreement_create, name="booking_agreement_create"),
    path("properties/<int:property_id>/plots/<int:plot_id>/bookings/<int:booking_id>/agreements/<int:agreement_id>/update/", views.booking_agreement_update, name="booking_agreement_update"),
    path("properties/<int:property_id>/plots/<int:plot_id>/bookings/<int:booking_id>/agreements/<int:agreement_id>/download/", views.booking_agreement_download, name="booking_agreement_download"),
    path("properties/<int:property_id>/plots/<int:plot_id>/bookings/<int:booking_id>/commissions/<int:payout_id>/update/", views.booking_commission_payout_update, name="booking_commission_payout_update"),
    path("properties/<int:property_id>/share-email/", views.property_share_email, name="share_email"),
    path("properties/<int:property_id>/plots/<int:plot_id>/", views.colony_plot_detail, name="plot_detail"),
    path("properties/<int:property_id>/plots/<int:plot_id>/pdf/", views.colony_plot_pdf, name="plot_pdf"),
    path("visits/", views.property_visit_index, name="visit_index"),
    path("properties/<int:property_id>/visits/", views.property_visit_list, name="visits"),
    path("properties/<int:property_id>/visits/new/", views.property_visit_create, name="visit_create"),
    path("properties/<int:property_id>/plots/<int:plot_id>/visits/new/", views.property_visit_create, name="plot_visit_create"),
    path("visits/<int:visit_id>/", views.property_visit_detail, name="visit_detail"),
    path("visits/<int:visit_id>/edit/", views.property_visit_edit, name="visit_edit"),
    path("visits/<int:visit_id>/delete/", views.property_visit_delete, name="visit_delete"),
]
