"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    return [item.strip() for item in os.environ.get(name, default).split(",") if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SIYA_SECRET_KEY", "django-insecure-local-development-only")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("SIYA_DEBUG", True)

ALLOWED_HOSTS = env_list("SIYA_ALLOWED_HOSTS", "127.0.0.1,localhost,testserver")
CSRF_TRUSTED_ORIGINS = env_list("SIYA_CSRF_TRUSTED_ORIGINS")
META_WEBHOOK_VERIFY_TOKEN = os.environ.get("SIYA_META_WEBHOOK_VERIFY_TOKEN", "siya-meta-local-verify")
META_GRAPH_API_VERSION = os.environ.get("SIYA_META_GRAPH_API_VERSION", "v20.0")
META_PAGE_ACCESS_TOKEN = os.environ.get("SIYA_META_PAGE_ACCESS_TOKEN", "")
META_APP_SECRET = os.environ.get("SIYA_META_APP_SECRET", "")


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "properties",
    "crm",
]

JAZZMIN_SETTINGS = {
    "site_title": "Siya Real Build Admin",
    "site_header": "Siya Real Build",
    "site_brand": "Siya Real Build",
    "site_logo": "img/siya-logo.jpg",
    "login_logo": "img/siya-logo.jpg",
    "welcome_sign": "Welcome to Siya Real Build Admin",
    "copyright": "Design and developed by The Webfix",
    "topmenu_links": [
        {"name": "Website", "url": "properties:dashboard", "permissions": ["auth.view_user"]},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accounts.context_processors.dashboard_access",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "properties:dashboard"
LOGOUT_REDIRECT_URL = "accounts:login"

EMAIL_BACKEND = os.environ.get(
    "SIYA_EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.environ.get("SIYA_EMAIL_HOST", "mail.thewebfix.in")
EMAIL_PORT = int(os.environ.get("SIYA_EMAIL_PORT", "465"))
EMAIL_USE_SSL = os.environ.get("SIYA_EMAIL_USE_SSL", "true").lower() == "true"
EMAIL_HOST_USER = os.environ.get("SIYA_EMAIL_HOST_USER", "noreply@thewebfix.in")
EMAIL_HOST_PASSWORD = os.environ.get("SIYA_EMAIL_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get(
    "SIYA_DEFAULT_FROM_EMAIL",
    "Siya Real Build <noreply@thewebfix.in>",
)

SECURE_SSL_REDIRECT = env_bool("SIYA_SECURE_SSL_REDIRECT", False)
SESSION_COOKIE_SECURE = env_bool("SIYA_SESSION_COOKIE_SECURE", False)
CSRF_COOKIE_SECURE = env_bool("SIYA_CSRF_COOKIE_SECURE", False)
SECURE_HSTS_SECONDS = int(os.environ.get("SIYA_SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SIYA_SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = env_bool("SIYA_SECURE_HSTS_PRELOAD", False)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

AUTH_RATE_LIMIT_WINDOW_SECONDS = int(os.environ.get("SIYA_AUTH_RATE_LIMIT_WINDOW_SECONDS", "900"))
AUTH_RATE_LIMIT_EMAIL_ATTEMPTS = int(os.environ.get("SIYA_AUTH_RATE_LIMIT_EMAIL_ATTEMPTS", "8"))
AUTH_RATE_LIMIT_IP_ATTEMPTS = int(os.environ.get("SIYA_AUTH_RATE_LIMIT_IP_ATTEMPTS", "30"))
SUPPORT_RATE_LIMIT_ATTEMPTS = int(os.environ.get("SIYA_SUPPORT_RATE_LIMIT_ATTEMPTS", "5"))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"standard": {"format": "{levelname} {asctime} {name} {message}", "style": "{"}},
    "handlers": {"console": {"class": "logging.StreamHandler", "formatter": "standard"}},
    "root": {"handlers": ["console"], "level": os.environ.get("SIYA_LOG_LEVEL", "INFO")},
}
