"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-k4@4_$r()^4pl05qqb$6dfxm8$k*zrtm-q$)8++kx&k+v37))&"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "testserver"]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "properties",
]

JAZZMIN_SETTINGS = {
    "site_title": "Siya Real Build Admin",
    "site_header": "Siya Real Build",
    "site_brand": "Siya Real Build",
    "site_logo": "img/siya-logo.jpg",
    "login_logo": "img/siya-logo.jpg",
    "welcome_sign": "Welcome to Siya Real Build Admin",
    "copyright": "Design and developed by The Webfix",
    "topmenu_links": [
        {"name": "Website", "url": "properties:dashboard", "permissions": ["auth.view_user"]},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "sandstone",
    "dark_mode_theme": "darkly",
    "navbar": "navbar-dark",
    "accent": "accent-warning",
    "sidebar": "sidebar-dark-warning",
    "brand_colour": "navbar-dark",
    "button_classes": {
        "primary": "btn-warning",
        "secondary": "btn-dark",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "properties:dashboard"
LOGOUT_REDIRECT_URL = "accounts:login"

EMAIL_BACKEND = os.environ.get(
    "SIYA_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.environ.get("SIYA_EMAIL_HOST", "mail.thewebfix.in")
EMAIL_PORT = int(os.environ.get("SIYA_EMAIL_PORT", "465"))
EMAIL_USE_SSL = os.environ.get("SIYA_EMAIL_USE_SSL", "true").lower() == "true"
EMAIL_HOST_USER = os.environ.get("SIYA_EMAIL_HOST_USER", "noreply@thewebfix.in")
EMAIL_HOST_PASSWORD = os.environ.get("SIYA_EMAIL_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get(
    "SIYA_DEFAULT_FROM_EMAIL",
    "Siya Real Build <noreply@thewebfix.in>",
)
