# Generated by Django 5.2.8 on 2026-06-11 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0032_referralreward_paid_at_referralreward_payout_note_and_more"),
        (
            "properties",
            "0006_property_assigned_to_propertyvisit_conversion_note_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=140)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=20)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("locality", models.CharField(blank=True, max_length=120)),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("requirement", models.TextField(blank=True)),
                (
                    "property_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("colony", "Colony"),
                            ("plot", "Plot"),
                            ("resale_plot", "Resale Plot"),
                            ("flat", "Flat"),
                            ("residential_house", "Residential House"),
                            ("commercial_shop", "Commercial Shop"),
                            ("row_house", "Row House"),
                            ("villa", "Villa"),
                            ("farm_house", "Farm House"),
                            ("office", "Office"),
                            ("warehouse", "Warehouse"),
                            ("agricultural_land", "Agricultural Land"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "listing_for",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sale", "Sale"),
                            ("rent", "Rent"),
                            ("lease", "Lease"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("meta", "Meta Lead Ads"),
                            ("manual", "Manual"),
                            ("website", "Website"),
                            ("referral", "Referral"),
                            ("whatsapp", "WhatsApp"),
                            ("property_share", "Property Share"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("source_reference", models.CharField(blank=True, max_length=160)),
                (
                    "meta_lead_id",
                    models.CharField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
                ("meta_form_id", models.CharField(blank=True, max_length=120)),
                ("meta_page_id", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("property_matched", "Property Matched"),
                            ("visit_scheduled", "Site Visit Scheduled"),
                            ("visit_completed", "Site Visit Completed"),
                            ("follow_up", "Follow-up"),
                            ("negotiation", "Negotiation"),
                            ("booked", "Booked"),
                            ("closed", "Closed"),
                            ("lost", "Lost"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="new",
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("next_follow_up_at", models.DateTimeField(blank=True, null=True)),
                ("last_contacted_at", models.DateTimeField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("lost_reason", models.CharField(blank=True, max_length=220)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_crm_lead_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_crm_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_leads",
                        to="accounts.companyprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_crm_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_leads",
                        to="properties.property",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_leads",
                        to="properties.propertyvisit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("status", "Status Changed"),
                            ("assigned", "Assigned"),
                            ("note", "Note"),
                            ("follow_up", "Follow-up"),
                            ("visit", "Site Visit"),
                            ("meta_sync", "Meta Sync"),
                        ],
                        max_length=30,
                    ),
                ),
                ("old_value", models.CharField(blank=True, max_length=220)),
                ("new_value", models.CharField(blank=True, max_length=220)),
                ("note", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadFollowUp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("done", "Done"),
                            ("missed", "Missed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, max_length=160)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["due_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MetaLeadSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_id", models.CharField(max_length=120)),
                ("page_name", models.CharField(blank=True, max_length=160)),
                ("form_id", models.CharField(max_length=120)),
                ("form_name", models.CharField(blank=True, max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("company_owner", "Company Owner"),
                            ("manager", "Manager"),
                            ("tl", "TL"),
                            ("executive", "Executive"),
                            ("channel_partner", "Channel Partner"),
                        ],
                        max_length=32,
                    ),
                ),
                ("field_mapping", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_lead_sources",
                        to="accounts.companyprofile",
                    ),
                ),
                (
                    "default_assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["page_name", "form_name"],
            },
        ),
        migrations.CreateModel(
            name="MetaWebhookEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=160, unique=True)),
                ("source", models.CharField(default="meta", max_length=80)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meta_webhook_events",
                        to="accounts.companyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["company", "status"], name="crm_lead_company_b1e111_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["company", "assigned_to"], name="crm_lead_company_4209ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["company", "source"], name="crm_lead_company_822dc2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="metaleadsource",
            unique_together={("company", "page_id", "form_id")},
        ),
    ]
