# Generated by Django 5.2.8 on 2026-06-11 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_referralreward_paid_at_referralreward_payout_note_and_more"),
        ("crm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadAssignmentRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("source", "Source Based"),
                            ("city", "City Based"),
                            ("category", "Property Category Based"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("meta", "Meta Lead Ads"),
                            ("manual", "Manual"),
                            ("website", "Website"),
                            ("referral", "Referral"),
                            ("whatsapp", "WhatsApp"),
                            ("property_share", "Property Share"),
                        ],
                        max_length=30,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=80)),
                (
                    "property_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("colony", "Colony"),
                            ("plot", "Plot"),
                            ("resale_plot", "Resale Plot"),
                            ("flat", "Flat"),
                            ("residential_house", "Residential House"),
                            ("commercial_shop", "Commercial Shop"),
                            ("row_house", "Row House"),
                            ("villa", "Villa"),
                            ("farm_house", "Farm House"),
                            ("office", "Office"),
                            ("warehouse", "Warehouse"),
                            ("agricultural_land", "Agricultural Land"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "default_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("company_owner", "Company Owner"),
                            ("manager", "Manager"),
                            ("tl", "TL"),
                            ("executive", "Executive"),
                            ("channel_partner", "Channel Partner"),
                        ],
                        max_length=32,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_assignment_rules",
                        to="accounts.companyprofile",
                    ),
                ),
                (
                    "default_assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_assignment_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "name"],
                "unique_together": {("company", "name")},
            },
        ),
    ]
