# Generated by Django 5.2.8 on 2026-06-11 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_referralreward_paid_at_referralreward_payout_note_and_more"),
        ("crm", "0002_leadassignmentrule"),
        (
            "properties",
            "0006_property_assigned_to_propertyvisit_conversion_note_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="archive_reason",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="lead",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_crm_leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leadassignmentrule",
            name="last_assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_used_crm_assignment_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leadassignmentrule",
            name="mode",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("source", "Source Based"),
                    ("city", "City Based"),
                    ("category", "Property Category Based"),
                    ("round_robin", "Round Robin"),
                    ("workload", "Workload Based"),
                ],
                default="default",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["company", "is_archived"], name="crm_lead_company_1e9235_idx"
            ),
        ),
    ]
